Added Zipped Folder for Part 1 of Node.JS Track
Part 1: Hello API Code-Along (See indiv. repo here: https://github.com/NicholasKyleHoffman/NodeJS-Track-Building-APIs-Part1)

Covers how to set up a simple Node.JS & Express.JS web app with API routes - GET & POST.

# Note: must unzip files onto your computer. 
Pre-Reqs:
- Have MongoDB Community Installed
- Have Postman installed
- Have Robo 3T installed

1. Open cmd prompt 1 & enter: npm install   ** if cmd prompt throws an error like "Error: Cannot find module 'body-parser' **
^ 1.b) npm install body-parser (or any other npm module that's missing - don't forget to "npm --save body-parser" to save it to our package.json file.

2. In cmd prompt 1, enter: mongod (to start database listening at specified port)

3. Open cmd prompt 2 & enter: nodemon server.js

4. In Postman, create following routes:
a) GET http://localhost:3000/api
b) POST http://localhost:3000/api/vehicles
c) GET http://localhost:3000/api/vehicle/60040237bf66f823082a8a65
d) GET http://localhost:3000/api/vehicle/color/grey

5) For each of the above HTTP API Routes, click "Send" button in Postman. You should see the different Vehicle objects output in response portion.

6) - OPTIONAL - Install Robo 3T. Open after running "nodemon server.js" and expand "codealong" DB to inspect objects contained in the Vehicles Collection.